// trending
export const FETCH_TRENDING_MOVIES_START = 'FETCH_TRENDING_MOVIES_START';
export const FETCH_TRENDING_MOVIES_SUCCESS = 'FETCH_TRENDING_MOVIES_SUCCESS';
export const FETCH_TRENDING_MOVIES_FAIL = 'FETCH_TRENDING_MOVIES_FAIL';

// upcoming
export const FETCH_UPCOMING_MOVIES_START = 'FETCH_UPCOMING_MOVIES_START';
export const FETCH_UPCOMING_MOVIES_SUCCESS = 'FETCH_UPCOMING_MOVIES_SUCCESS';
export const FETCH_UPCOMING_MOVIES_FAIL = 'FETCH_UPCOMING_MOVIES_FAIL';

// search
export const SEARCH_START = 'SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

//auth
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

//watchlist 
export const FETCH_WL_START = 'FETCH_WL_START'
export const FETCH_WL_SUCCESS = 'FETCH_WL_SUCCESS'
export const FETCH_WL_FAIL = 'FETCH_WL_FAIL'
